databases:
  - name: personal-postgtres-instance
    plan: free
    databaseName: n2mobil
    user: yunusemre482

services:
  - type: web
    plan: free
    name: n2mobil-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personal-postgtres-instance
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4