# Generated by Django 4.2.14 on 2024-07-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
